version: '3.5'

services:
  ravendb:
    container_name: food-ordering
    image: ravendb/ravendb
    ports:
      - 8080:8080
    environment:
      - RAVEN_Security_UnsecuredAccessAllowed=PublicNetwork
      - RAVEN_ARGS="--Setup.Mode=None"

# services:
#   postgres:
#     image: postgres
#     shm_size: '4gb'
#     container_name: postgres
#     restart: unless-stopped
#     environment:
#       - POSTGRES_HOST_AUTH_METHOD=trust
#     ports:
#       - 5432:5432
#     volumes:
#       - postgres:/var/lib/postgresql/data

# volumes:
#   postgres:
#     driver: local
